# Generated by Django 6.0.6 on 2026-07-04 23:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=500)),
                ('source_type', models.CharField(choices=[('meet', 'Meeting'), ('dictaphone', 'Dictaphone'), ('upload', 'Upload'), ('other', 'Other')], default='upload', max_length=32)),
                ('asr_tier', models.CharField(choices=[('fast', 'Fast'), ('accurate', 'Accurate')], default='fast', max_length=16)),
                ('language_mode', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual'), ('multilingual', 'Multilingual')], default='auto', max_length=16)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('diarization_enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('uploading', 'Uploading'), ('queued', 'Queued'), ('analyzing', 'Analyzing'), ('normalizing', 'Normalizing'), ('transcribing', 'Transcribing'), ('diarizing', 'Diarizing'), ('merging', 'Merging'), ('completed', 'Completed'), ('error', 'Error'), ('deleted', 'Deleted')], default='created', max_length=32)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('file_storage_key', models.CharField(blank=True, max_length=512, null=True)),
                ('normalized_storage_key', models.CharField(blank=True, max_length=512, null=True)),
                ('transcript_storage_key', models.CharField(blank=True, max_length=512, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('segments_count', models.IntegerField(default=0)),
                ('speakers_count', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('confidence_avg', models.FloatField(blank=True, null=True)),
                ('provider_used', models.CharField(blank=True, max_length=64, null=True)),
                ('provider_override', models.CharField(blank=True, max_length=64, null=True)),
                ('fallback_used', models.BooleanField(default=False)),
                ('processing_latency_ms', models.IntegerField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recordings_recording',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('type', models.CharField(choices=[('full_pipeline', 'Full Pipeline'), ('normalize_audio', 'Normalize Audio'), ('transcribe', 'Transcribe'), ('diarize', 'Diarize'), ('merge', 'Merge'), ('summarize', 'Summarize')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('progress_percent', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=64, null=True)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.JSONField(blank=True, null=True)),
                ('provider_used', models.CharField(blank=True, max_length=64, null=True)),
                ('processing_latency_ms', models.IntegerField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recording_jobs', to=settings.AUTH_USER_MODEL)),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='recordings.recording')),
            ],
            options={
                'db_table': 'recordings_job',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Provider label, e.g. speaker_0', max_length=64)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_duration_seconds', models.FloatField(default=0)),
                ('segment_count', models.IntegerField(default=0)),
                ('color', models.CharField(default='#4A90D9', max_length=7)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='recordings.recording')),
            ],
            options={
                'db_table': 'recordings_speaker',
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_num', models.IntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('text', models.TextField()),
                ('original_text', models.TextField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('word_count', models.IntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('words_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='recordings.recording')),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='recordings.speaker')),
            ],
            options={
                'db_table': 'recordings_segment',
                'ordering': ['recording', 'sequence_num'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('presigned_url', models.TextField(blank=True)),
                ('storage_key', models.CharField(max_length=512)),
                ('max_size_bytes', models.BigIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_multipart', models.BooleanField(default=False)),
                ('multipart_upload_id', models.CharField(blank=True, max_length=512, null=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='recordings.recording')),
            ],
            options={
                'db_table': 'recordings_upload_session',
            },
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['workspace_id', 'status'], name='rec_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['owner'], name='rec_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['status', 'updated_at'], name='rec_status_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['deleted_at'], name='rec_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['workspace_id', 'status'], name='rec_job_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['recording'], name='rec_job_rec_idx'),
        ),
        migrations.AddIndex(
            model_name='speaker',
            index=models.Index(fields=['recording'], name='rec_speaker_rec_idx'),
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['recording', 'sequence_num'], name='rec_seg_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['speaker'], name='rec_seg_speaker_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['recording'], name='rec_upload_rec_idx'),
        ),
    ]
