# Generated by Django 6.0.7 on 2026-08-13 23:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_speaker_ordering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_token_hash', models.CharField(max_length=64, unique=True)),
                ('passcode_hash', models.CharField(blank=True, default='', max_length=255)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('token_version', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.BigIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_unlock_count', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recording_shares', to=settings.AUTH_USER_MODEL)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='recordings.recording')),
            ],
            options={
                'db_table': 'recordings_share',
                'indexes': [models.Index(fields=['recording'], name='rec_share_rec_idx'), models.Index(fields=['link_token_hash'], name='rec_share_token_idx')],
            },
        ),
    ]
